version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    environment:
      - ENABLE_INIT_DAEMON=false
    external_links:
      - spark-master
    networks:
      - fractals-cluster_default
networks:
  fractals-cluster_default:
    external: true


